// Writes the backend address (API_URL environment variable) into src/app/core/web-config.ts before a hosted build.
// Usage: API_URL=https://money-monitor-api.onrender.com node scripts/set-api-url.mjs
import { writeFileSync } from 'node:fs';

const url = (process.env.API_URL ?? '').trim().replace(/\/+$/, '');
if (!url) {
  console.error('API_URL is not set. In Netlify: Site configuration > Environment variables > API_URL = your Render address.');
  process.exit(1);
}
if (!/^https:\/\//.test(url)) {
  console.error(`API_URL must start with https:// (got "${url}").`);
  process.exit(1);
}

writeFileSync(
  new URL('../src/app/core/web-config.ts', import.meta.url),
  `// Generated by scripts/set-api-url.mjs during the hosted build.\nexport const WEB_SERVER_URL = ${JSON.stringify(url)};\n`,
);
console.log(`Backend address set to ${url}`);
